Repository arborrow/montserrat, pull requests merged in 2019-05, with the labels that each got.

#301 Data corruption - creating bad bishops when updating a Diocese (fix #300)
  app/Contact.php
  app/Http/Controllers/DioceseController.php
Labels: critical bug

#315 Add ability to send emails on exceptions (fix #207)
  app/Exceptions/Handler.php
  resources/views/emails/error.blade.php
  resources/views/errors/503.blade.php
  resources/views/errors/default.blade.php
Labels: in progress

#326 Remove reference to envelop10 css file
  resources/assets/fonts/perpetua.ttf
  resources/assets/sass/print-envelope10.scss
  resources/assets/sass/print-landscape.scss
  resources/assets/sass/print-style.scss
  resources/views/envelope10.blade.php
  resources/views/report.blade.php
  resources/views/reportlandscape.blade.php
  webpack.mix.js
Labels: ready for review
